import Head from 'next/head'
import Navbar from '../components/Navbar'
import { table, sortingRecords } from './api/utils/airtableHelper'
import { ToDosContext } from '../contexts/ToDosContext'
import { useEffect, useContext } from 'react'
import { useUser } from '@auth0/nextjs-auth0';
import UserContent from '../components/UserContent'

export default function Home({initialTodos}) {
  const { user, isLoading } = useUser();
  const {todos, setTodos} = useContext(ToDosContext);
  useEffect(()=>{
    setTodos(initialTodos)
  },[])
  
  return (
    <div>
      <Head>
        <title>My ToDo application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {!user && 
          <p>login to check your todo list</p>
        }
        { isLoading &&
          <p>...Loading...</p>
        }
        { user && 
          <UserContent todos={todos}/>
        }
      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  try{
    const firstTodos = await table.select({}).firstPage();
    return {
      props: {
        initialTodos : sortingRecords(firstTodos)
      }
    }
  }catch(err){
    console.error(err)
    return{
      props : {
        err : "Something went wrong!..."
      }
    }
  }
}
