import Head from 'next/head'
import Navbar from '../components/Navbar'
import { table, sortingRecords } from './api/utils/airtableHelper'


export default function Home({initialTodos}) {
  console.log(initialTodos)
  return (
    <div>
      <Head>
        <title>My ToDo application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <h1>My ToDo application </h1>
      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  try{
    const todos = await table.select({}).firstPage();
    return {
      props: {
        initialTodos : sortingRecords(todos)
      }
    }
  }catch(err){
    console.error(err)
    return{
      props : {
        err : "Something went wrong!..."
      }
    }
  }
}
